theme: jekyll-theme-minimal
logo: https://www.researchgate.net/profile/Jonathan-Zia-2/publication/335795238/figure/fig2/AS:815386123583488@1571414609208/a-Clustering-of-features-corresponding-to-the-first-minimum-of-SCG-segments-for-signals_W640.jpg
